name: CI Calculate App
on:
  push:
    branches: [master]
env:
  PYTHON-ENV: ci-app-python-123
  SIMPLE-CODE: 123
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Create env and install dependencies
        run: poetry install --no-interaction --no-root

      - name: Check code formatting with Black
        run: poetry run black --check .

  test:
    needs: black
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Create env and install dependencies
        run: poetry install --no-interaction --no-root

      - name: Testing App
        run: poetry run pytest -s -v --html=test_report.html --self-contained-html

      - name: Upload Test-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: testing-report-${{ matrix.runs-on }}
          path: test_report.html

  deploy:
    runs-on: ubuntu-latest
    needs: [test, black]
    steps:
      - name: Download Test-Report
        uses: actions/download-artifact@v4
        with:
          pattern: testing-report-*
          merge-multiple: true
      - name: Deploy App
        run: |
          echo Test-Deploy App with code ${{ env.SIMPLE-CODE }}
          echo Deploy App to Server with code ${{ secrets.DEPLOY_CODE }} ...     
