name: Test App with Docker
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - name: Use Custom Action
        uses: ./.github/actions/cache-poetry
      - name: Test Users
        run: poetry run pytest -v
