name: Test App with Docker
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/checkout@v4

      - name: Use Custom Action
        uses: ./.github/actions/cache-poetry
        with:
          caching: 'false'

      - name: Test Users
        run: poetry run pytest -v
