name: World
on:
  workflow_run:
    workflows: [Demo workflow]
    types:
      - completed

jobs:
  success-hello:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'say hello => success'

  failed-hello:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'say hello => failed'
